// src/tools/report-generator/pdfStyles.ts
import { PDFPage, PDFFont, PDFDocument, rgb, degrees, type RGB, PageSizes } from 'pdf-lib';

// ═══════════════════════════════════════════════════════
// Page Dimensions (A4)
// ═══════════════════════════════════════════════════════
export const PAGE_WIDTH = PageSizes.A4[0]; // 595.28
export const PAGE_HEIGHT = PageSizes.A4[1]; // 841.89
export const MARGIN = 40;
export const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;

// ═══════════════════════════════════════════════════════
// Brand Colors
// ═══════════════════════════════════════════════════════
export const COLORS = {
    brandBlue: rgb(0.247, 0.318, 0.71),
    brandTeal: rgb(0, 0.588, 0.533),
    brandTealLight: rgb(0.2, 0.78, 0.45),

    success: rgb(0.1, 0.7, 0.3),
    successBg: rgb(0.9, 0.97, 0.91),
    successLight: rgb(0.6, 0.92, 0.7),
    failure: rgb(0.8, 0.15, 0.15),
    failureBg: rgb(0.98, 0.91, 0.91),
    failureLight: rgb(0.95, 0.7, 0.7),

    textDark: rgb(0.1, 0.1, 0.12),
    textMedium: rgb(0.3, 0.3, 0.35),
    textLight: rgb(0.5, 0.5, 0.55),
    textMuted: rgb(0.65, 0.65, 0.7),
    white: rgb(1, 1, 1),

    bgLight: rgb(0.96, 0.96, 0.97),
    bgMedium: rgb(0.92, 0.92, 0.94),
    bgDark: rgb(0.15, 0.16, 0.2),
    bgHeader: rgb(0.12, 0.13, 0.17),

    terrainFill: rgb(0.78, 0.87, 0.95),
    terrainStroke: rgb(0.4, 0.55, 0.75),
    losLineClear: rgb(0.1, 0.75, 0.4),
    losLineBlocked: rgb(0.85, 0.2, 0.2),
    obstructionDot: rgb(0.9, 0.15, 0.15),
    towerLine: rgb(0.85, 0.7, 0.2),
    towerHandle: rgb(0.9, 0.75, 0.25),
    gridLine: rgb(0.85, 0.85, 0.88),
    chartBg: rgb(0.98, 0.98, 0.99),
    chartBorder: rgb(0.82, 0.82, 0.85),

    borderLight: rgb(0.85, 0.85, 0.88),
    borderMedium: rgb(0.75, 0.75, 0.78),

    fiberBlue: rgb(0.2, 0.5, 0.9),

    // Device compatibility colors
    deviceCompatible: rgb(0.086, 0.639, 0.290),
    deviceIncompatible: rgb(0.863, 0.149, 0.149),
    utilizationBarBg: rgb(0.898, 0.906, 0.922),
    utilizationBarFill: rgb(0.247, 0.318, 0.71),
    utilizationBarDanger: rgb(0.863, 0.149, 0.149),
} as const;

// ═══════════════════════════════════════════════════════
// Font Sizes
// ═══════════════════════════════════════════════════════
export const FONT_SIZES = {
    title: 18,
    sectionHeader: 11,
    body: 9.5,
    bodySmall: 8.5,
    label: 7.5,
    footer: 7,
    watermark: 36,
    statusBanner: 14,
    statusDetail: 9,
    metricValue: 11,
    metricLabel: 7,
    chartAxis: 7,
    chartLabel: 8,
} as const;

// ═══════════════════════════════════════════════════════
// Branding Constants
// ═══════════════════════════════════════════════════════
export const BRANDING = {
    companyName: 'Nav Wireless Technologies Pvt. Ltd.',
    productName: 'FindLOS',
    domain: 'findlos.com',
    reportTitle: 'LOS Feasibility Report',
    fiberReportTitle: 'Fiber Path Analysis Report',
    combinedReportTitle: 'LOS Feasibility Analysis',
    footerText: 'Generated by FindLOS (findlos.com) | Nav Wireless Technologies Pvt. Ltd.',
    /** @deprecated Removed from report headers to avoid duplication with footer. Kept for backward compat. */
    poweredBy: '',
    logoUrl: '',
} as const;

// ═══════════════════════════════════════════════════════
// Report ID Generator
// Format: NN-hhmmddmmyy-CDD
// ═══════════════════════════════════════════════════════
export function generateReportId(
    userName: string,
    sequenceNumber: number,
    seriesLetter?: string,
): string {
    const nameParts = (userName || '').trim().split(/\s+/).filter(Boolean);
    let initials = 'XX';
    if (nameParts.length >= 2) {
        initials = (nameParts[0][0] + nameParts[1][0]).toUpperCase();
    } else if (nameParts.length === 1 && nameParts[0].length >= 2) {
        initials = nameParts[0].substring(0, 2).toUpperCase();
    } else if (nameParts.length === 1 && nameParts[0].length === 1) {
        initials = (nameParts[0][0] + 'X').toUpperCase();
    }

    const now = new Date();
    const hh = String(now.getHours()).padStart(2, '0');
    const mm = String(now.getMinutes()).padStart(2, '0');
    const dd = String(now.getDate()).padStart(2, '0');
    const mo = String(now.getMonth() + 1).padStart(2, '0');
    const yy = String(now.getFullYear()).slice(-2);
    const timestamp = `${hh}${mm}${dd}${mo}${yy}`;

    const letter = seriesLetter || 'A';
    const seqNum = Math.max(1, Math.min(99, sequenceNumber));
    const seqStr = String(seqNum).padStart(2, '0');

    return `${initials}-${timestamp}-${letter}${seqStr}`;
}

// ═══════════════════════════════════════════════════════
// Sanitize text for WinAnsi encoding
// ═══════════════════════════════════════════════════════
export function sanitize(str: string): string {
    return str
        .replace(/→/g, '->')
        .replace(/←/g, '<-')
        .replace(/…/g, '...')
        .replace(/—/g, '--')
        .replace(/–/g, '-')
        .replace(/\u2018|\u2019/g, "'")
        .replace(/\u201C|\u201D/g, '"')
        .replace(/•/g, '-')
        .replace(/\u2713/g, 'PASS')
        .replace(/\u2717/g, 'FAIL')
        .replace(/[^\x20-\x7E\xA0-\xFF]/g, '');
}

// ═══════════════════════════════════════════════════════
// Draw filled box with optional border
// ═══════════════════════════════════════════════════════
export function drawBox(
    page: PDFPage,
    x: number,
    y: number,
    width: number,
    height: number,
    fillColor: RGB,
    borderColor?: RGB,
    borderWidth?: number,
) {
    page.drawRectangle({ x, y, width, height, color: fillColor });
    if (borderColor) {
        page.drawRectangle({
            x, y, width, height,
            borderColor,
            borderWidth: borderWidth ?? 0.5,
        });
    }
}

// ═══════════════════════════════════════════════════════
// Fetch Logo Image Bytes
// ═══════════════════════════════════════════════════════
export async function fetchLogoBytes(url?: string): Promise<Uint8Array | undefined> {
    const logoUrl = url || BRANDING.logoUrl;
    if (!logoUrl) return undefined;
    try {
        const response = await fetch(logoUrl);
        if (!response.ok) {
            console.warn(`PDF: Failed to fetch logo: ${response.status} from ${logoUrl}`);
            return undefined;
        }
        const arrayBuffer = await response.arrayBuffer();
        return new Uint8Array(arrayBuffer);
    } catch (error) {
        console.warn('PDF: Error fetching logo:', error);
        return undefined;
    }
}

// ═══════════════════════════════════════════════════════
// Branded Header — returns Y below header
// ═══════════════════════════════════════════════════════
export async function drawBrandedHeader(
    page: PDFPage,
    fonts: { regular: PDFFont; bold: PDFFont },
    pdfDoc: PDFDocument,
    title?: string,
    logoBytes?: Uint8Array,
): Promise<number> {
    const reportTitle = title || BRANDING.reportTitle;
    const headerY = PAGE_HEIGHT - MARGIN;
    let logoDrawn = false;

    if (logoBytes) {
        try {
            const logoImage = await pdfDoc.embedPng(logoBytes);
            const logoMaxH = 28;
            const scale = logoMaxH / logoImage.height;
            const logoW = logoImage.width * scale;
            const logoH = logoMaxH;
            page.drawImage(logoImage, {
                x: MARGIN,
                y: headerY - logoH,
                width: logoW,
                height: logoH,
            });
            logoDrawn = true;
        } catch {
            // Logo embed failed — fall back to text
        }
    }

    if (!logoDrawn) {
        page.drawText(BRANDING.companyName, {
            x: MARGIN,
            y: headerY - 12,
            font: fonts.bold,
            size: 9,
            color: COLORS.textMedium,
        });
    }

    const titleWidth = fonts.bold.widthOfTextAtSize(reportTitle, FONT_SIZES.title);
    page.drawText(reportTitle, {
        x: PAGE_WIDTH - MARGIN - titleWidth,
        y: headerY - 16,
        font: fonts.bold,
        size: FONT_SIZES.title,
        color: COLORS.textDark,
    });

    const lineY = headerY - 32;
    page.drawLine({
        start: { x: MARGIN, y: lineY },
        end: { x: PAGE_WIDTH - MARGIN, y: lineY },
        thickness: 1,
        color: COLORS.borderLight,
    });

    return lineY - 8;
}

// ═══════════════════════════════════════════════════════
// Branded Footer
// ═══════════════════════════════════════════════════════
export function drawBrandedFooter(
    page: PDFPage,
    font: PDFFont,
    pageNumber: number,
    totalPages: number,
) {
    const footerY = MARGIN - 18;

    page.drawLine({
        start: { x: MARGIN, y: footerY + 12 },
        end: { x: PAGE_WIDTH - MARGIN, y: footerY + 12 },
        thickness: 0.5,
        color: COLORS.borderLight,
    });

    page.drawText(BRANDING.footerText, {
        x: MARGIN,
        y: footerY,
        font,
        size: FONT_SIZES.footer,
        color: COLORS.textMuted,
    });

    const pageText = `Page ${pageNumber} of ${totalPages}`;
    const pageWidth = font.widthOfTextAtSize(pageText, FONT_SIZES.footer);
    page.drawText(pageText, {
        x: PAGE_WIDTH - MARGIN - pageWidth,
        y: footerY,
        font,
        size: FONT_SIZES.footer,
        color: COLORS.textMuted,
    });
}

// ═══════════════════════════════════════════════════════
// Watermark — diagonal semi-transparent
// ═══════════════════════════════════════════════════════
export function drawWatermark(page: PDFPage, font: PDFFont) {
    const text = BRANDING.domain.toUpperCase();
    const size = FONT_SIZES.watermark;
    const textWidth = font.widthOfTextAtSize(text, size);

    page.drawText(text, {
        x: (PAGE_WIDTH - textWidth) / 2,
        y: PAGE_HEIGHT / 2 - 10,
        font,
        size,
        color: rgb(0.92, 0.92, 0.94),
        opacity: 0.07,
        rotate: degrees(-35),
    });
}

// ═══════════════════════════════════════════════════════
// Section Header — colored left bar + tinted background
// ═══════════════════════════════════════════════════════
export function drawSectionHeader(
    page: PDFPage,
    font: PDFFont,
    text: string,
    y: number,
    color?: RGB,
): number {
    const headerColor = color || COLORS.brandBlue;

    page.drawRectangle({
        x: MARGIN,
        y: y - 14,
        width: CONTENT_WIDTH,
        height: 16,
        color: rgb(
            Math.min(1, headerColor.red * 0.15 + 0.92),
            Math.min(1, headerColor.green * 0.15 + 0.92),
            Math.min(1, headerColor.blue * 0.15 + 0.92),
        ),
    });

    page.drawRectangle({
        x: MARGIN,
        y: y - 14,
        width: 3,
        height: 16,
        color: headerColor,
    });

    page.drawText(sanitize(text), {
        x: MARGIN + 10,
        y: y - 10,
        font,
        size: FONT_SIZES.sectionHeader,
        color: headerColor,
    });

    return y - 22;
}

// ═══════════════════════════════════════════════════════
// Key-Value Row
// ═══════════════════════════════════════════════════════
export function drawKeyValue(
    page: PDFPage,
    fonts: { regular: PDFFont; bold: PDFFont },
    key: string,
    value: string,
    y: number,
    options?: {
        keyX?: number;
        valueX?: number;
        valueColor?: RGB;
    },
): number {
    const keyX = options?.keyX ?? MARGIN + 5;
    const valueX = options?.valueX ?? MARGIN + 140;
    const valueColor = options?.valueColor ?? COLORS.textDark;

    page.drawText(sanitize(key) + ':', {
        x: keyX,
        y,
        font: fonts.regular,
        size: FONT_SIZES.body,
        color: COLORS.textMedium,
    });

    page.drawText(sanitize(value), {
        x: valueX,
        y,
        font: fonts.bold,
        size: FONT_SIZES.body,
        color: valueColor,
    });

    return y - 13;
}

// ═══════════════════════════════════════════════════════
// Date Formatter
// ═══════════════════════════════════════════════════════
export function formatReportDate(dateStr?: string): string {
    const date = dateStr ? new Date(dateStr) : new Date();
    return date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });
}

// ═══════════════════════════════════════════════════════
// Wrap text to fit within maxWidth
// ═══════════════════════════════════════════════════════
export function wrapText(
    text: string,
    font: PDFFont,
    fontSize: number,
    maxWidth: number,
): string[] {
    const sanitized = sanitize(text);
    const words = sanitized.split(' ');
    const lines: string[] = [];
    let currentLine = '';

    for (const word of words) {
        const testLine = currentLine ? `${currentLine} ${word}` : word;
        const testWidth = font.widthOfTextAtSize(testLine, fontSize);

        if (testWidth > maxWidth && currentLine) {
            lines.push(currentLine);
            currentLine = word;
        } else {
            currentLine = testLine;
        }
    }

    if (currentLine) {
        lines.push(currentLine);
    }

    return lines;
}

// ═══════════════════════════════════════════════════════
// Utilization Bar — KEPT for backward compat
// ═══════════════════════════════════════════════════════
export function drawUtilizationBar(
    page: PDFPage,
    font: PDFFont,
    x: number,
    y: number,
    width: number,
    height: number,
    percent: number,
    label?: string,
): void {
    const clampedPercent = Math.max(0, Math.min(100, percent));
    const fillWidth = (clampedPercent / 100) * width;
    const fillColor = clampedPercent > 90 ? COLORS.utilizationBarDanger : COLORS.utilizationBarFill;

    page.drawRectangle({ x, y, width, height, color: COLORS.utilizationBarBg });
    if (fillWidth > 0) {
        page.drawRectangle({ x, y, width: fillWidth, height, color: fillColor });
    }
    page.drawRectangle({ x, y, width, height, borderColor: COLORS.borderLight, borderWidth: 0.3 });

    const pctText = label || `${clampedPercent.toFixed(0)}%`;
    const pctW = font.widthOfTextAtSize(pctText, 6.5);

    if (fillWidth > pctW + 6) {
        page.drawText(pctText, {
            x: x + fillWidth - pctW - 3,
            y: y + (height - 5) / 2,
            font, size: 6.5, color: COLORS.white,
        });
    } else {
        page.drawText(pctText, {
            x: x + width + 4,
            y: y + (height - 5) / 2,
            font, size: 6.5, color: COLORS.textMedium,
        });
    }
}

// ═══════════════════════════════════════════════════════
// Client Info Block
// ═══════════════════════════════════════════════════════
export function drawClientInfoBlock(
    page: PDFPage,
    fonts: { regular: PDFFont; bold: PDFFont },
    y: number,
    config: {
        clientName?: string;
        projectName?: string;
        preparedBy?: string;
        referenceNumber?: string;
        date?: string;
    },
): number {
    const hasAnyField = config.clientName || config.projectName || config.preparedBy || config.referenceNumber;
    if (!hasAnyField) return y;

    const startY = y;
    const leftCol = MARGIN + 5;
    const rightCol = MARGIN + CONTENT_WIDTH / 2;
    let leftY = startY;
    let rightY = startY;

    if (config.clientName) {
        page.drawText('Prepared for:', {
            x: leftCol, y: leftY,
            font: fonts.regular, size: FONT_SIZES.bodySmall, color: COLORS.textLight,
        });
        leftY -= 10;
        page.drawText(sanitize(config.clientName), {
            x: leftCol, y: leftY,
            font: fonts.bold, size: FONT_SIZES.body, color: COLORS.textDark,
        });
        leftY -= 14;
    }

    if (config.projectName) {
        page.drawText('Project:', {
            x: leftCol, y: leftY,
            font: fonts.regular, size: FONT_SIZES.bodySmall, color: COLORS.textLight,
        });
        leftY -= 10;
        page.drawText(sanitize(config.projectName), {
            x: leftCol, y: leftY,
            font: fonts.bold, size: FONT_SIZES.body, color: COLORS.textDark,
        });
        leftY -= 14;
    }

    if (config.preparedBy) {
        page.drawText('Prepared by:', {
            x: rightCol, y: rightY,
            font: fonts.regular, size: FONT_SIZES.bodySmall, color: COLORS.textLight,
        });
        rightY -= 10;
        page.drawText(sanitize(config.preparedBy), {
            x: rightCol, y: rightY,
            font: fonts.bold, size: FONT_SIZES.body, color: COLORS.textDark,
        });
        rightY -= 14;
    }

    if (config.referenceNumber) {
        page.drawText('Reference:', {
            x: rightCol, y: rightY,
            font: fonts.regular, size: FONT_SIZES.bodySmall, color: COLORS.textLight,
        });
        rightY -= 10;
        page.drawText(sanitize(config.referenceNumber), {
            x: rightCol, y: rightY,
            font: fonts.bold, size: FONT_SIZES.body, color: COLORS.textDark,
        });
        rightY -= 14;
    }

    if (config.date) {
        const dateLabel = `Date: ${formatReportDate(config.date)}`;
        const dateW = fonts.regular.widthOfTextAtSize(dateLabel, FONT_SIZES.bodySmall);
        page.drawText(dateLabel, {
            x: PAGE_WIDTH - MARGIN - dateW, y: startY,
            font: fonts.regular, size: FONT_SIZES.bodySmall, color: COLORS.textLight,
        });
    }

    const bottomY = Math.min(leftY, rightY);

    page.drawLine({
        start: { x: MARGIN, y: bottomY },
        end: { x: PAGE_WIDTH - MARGIN, y: bottomY },
        thickness: 0.4,
        color: COLORS.borderLight,
    });

    return bottomY - 6;
}