"use client";

import { useCallback, useState } from 'react';
import type { AnalysisResult } from '@/types';
import type { FiberPathResult } from '@/tools/fiberPathCalculator/types';
import type { ExportConfig } from '@/tools/report-generator/types';

// ============================================
// Types
// ============================================

export interface UseWhatsAppShareOptions {
  /** Toast notification function */
  toast: (opts: {
    title: string;
    description?: string;
    variant?: 'default' | 'destructive';
  }) => void;
}

export interface UseWhatsAppShareReturn {
  /** Whether a share is currently in progress */
  isSharing: boolean;
  /** Initiates the WhatsApp share flow */
  shareViaWhatsApp: (
    analysisResult: AnalysisResult,
    fiberResult?: FiberPathResult | null,
    exportConfig?: ExportConfig,
  ) => Promise<void>;
}

// ============================================
// Message Template
// ============================================

function buildWhatsAppMessage(result: AnalysisResult): string {
  const siteAName = result.pointA?.name || 'Site A';
  const siteBName = result.pointB?.name || 'Site B';
  const distance = result.distanceKm.toFixed(2);
  const feasibility = result.losPossible ? '✓ FEASIBLE' : '✗ BLOCKED';

  let deviceLine = '';
  if (result.deviceCompatibility?.selectedDevice) {
    const dev = result.deviceCompatibility.selectedDevice;
    const compat = dev.isCompatible ? 'Compatible' : 'Not Compatible';
    deviceLine = `\n📶 Device: ${dev.deviceName} — ${compat}`;
  } else if (result.deviceCompatibility?.recommendation?.recommendedDeviceName) {
    deviceLine = `\n📶 Recommended: ${result.deviceCompatibility.recommendation.recommendedDeviceName}`;
  }

  const message = [
    '📡 LOS Feasibility Report',
    '',
    `📍 ${siteAName} → ${siteBName}`,
    `📏 Distance: ${distance} km`,
    feasibility,
    deviceLine,
    '',
    'Generated by FindLOS (findlos.com)',
    `Report ID: ${result.id}`,
  ]
    .filter((line) => line !== undefined)
    .join('\n');

  return message;
}

// ============================================
// Hook
// ============================================

/**
 * Hook for sharing analysis results via WhatsApp.
 *
 * Flow:
 * 1. Generate PDF report via server action
 * 2. Download PDF to device
 * 3. Open WhatsApp with pre-filled message
 * 4. User manually attaches downloaded PDF in WhatsApp chat
 *
 * @example
 * const { isSharing, shareViaWhatsApp } = useWhatsAppShare({ toast });
 * // ...
 * await shareViaWhatsApp(analysisResult, fiberResult);
 */
export function useWhatsAppShare({
  toast,
}: UseWhatsAppShareOptions): UseWhatsAppShareReturn {
  const [isSharing, setIsSharing] = useState(false);

  const shareViaWhatsApp = useCallback(
    async (
      analysisResult: AnalysisResult,
      fiberResult?: FiberPathResult | null,
      exportConfig?: ExportConfig,
    ) => {
      setIsSharing(true);

      try {
        // 1. Generate and download PDF
        const [{ saveAs }, { generateSingleAnalysisPdfReportAction }] =
          await Promise.all([
            import('file-saver'),
            import('@/app/actions'),
          ]);

        const reportOptions: Record<string, unknown> = {};
        if (exportConfig) {
          reportOptions.exportConfig = exportConfig;
        }

        const response = await generateSingleAnalysisPdfReportAction(
          analysisResult,
          reportOptions,
          fiberResult,
        );

        if (response.success) {
          const { base64Pdf, fileName } = response.data;
          const byteCharacters = atob(base64Pdf);
          const byteNumbers = new Array(byteCharacters.length);
          for (let i = 0; i < byteCharacters.length; i++) {
            byteNumbers[i] = byteCharacters.charCodeAt(i);
          }
          const byteArray = new Uint8Array(byteNumbers);
          const blob = new Blob([byteArray], { type: 'application/pdf' });
          saveAs(blob, fileName);

          // 2. Open WhatsApp with pre-filled message
          const message = buildWhatsAppMessage(analysisResult);
          const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(message)}`;

          // Small delay so the download starts before navigating
          setTimeout(() => {
            window.open(whatsappUrl, '_blank', 'noopener,noreferrer');
          }, 500);

          toast({
            title: 'Report Downloaded',
            description:
              'PDF downloaded! Attach it in the WhatsApp chat that just opened.',
          });
        } else {
          throw new Error(response.error);
        }
      } catch (error) {
        const errorMessage =
          error instanceof Error
            ? error.message
            : 'Failed to generate report for sharing.';
        console.error('WhatsApp share error:', error);
        toast({
          title: 'Share Failed',
          description: errorMessage,
          variant: 'destructive',
        });
      } finally {
        setIsSharing(false);
      }
    },
    [toast]
  );

  return {
    isSharing,
    shareViaWhatsApp,
  };
}